# Generated by Django 5.1.3 on 2024-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_project_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateField(),
        ),
    ]
